version: "3.9"
services:
  saku:
    image: "ghcr.io/yummiii/saku:master"
    container_name: "saku"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root:root@saku_db/Saku
  db:
    image: "mariadb:10.5"
    container_name: "saku_db"
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=Saku

volumes:
  mariadb: