version: "3.9"
services:
  saku:
    image: "ghcr.io/yummiii/saku:master"
    container_name: "saku"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/app/    

volumes:
  db-data: